config/routes.rb
Calendar::Application.routes.draw do
  root 'sessions#new'
  get '/sessions/new' => 'sessions#new', :as => 'new_session'
  post '/sessions' => 'sessions#create', :as => 'sessions'
  delete '/sessions' => 'sessions#destroy', :as => 'session'

  resources :events

  resources :questions

  resources :responses

  get '/users/home' => 'users#home', :as => 'home'
  resources :users

end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  before_action :set_response, only: [:show, :edit, :update, :destroy]

  # GET /responses
  # GET /responses.json
  def index
    @responses = Response.all
  end

  # GET /responses/1
  # GET /responses/1.json
  def show
  end

  # GET /responses/new
  def new
    @response = Response.new
  end

  # GET /responses/1/edit
  def edit
  end

  # POST /responses
  # POST /responses.json
  def create
    @response = Response.new(response_params)

    respond_to do |format|
      if @response.save
        format.html { redirect_to @response, notice: 'Response was successfully created.' }
        format.json { render action: 'show', status: :created, location: @response }
      else
        format.html { render action: 'new' }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /responses/1
  # PATCH/PUT /responses/1.json
  def update

    respond_to do |format|
      if @response.update(response_params)
        format.html { redirect_to @response, notice: 'Response was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /responses/1
  # DELETE /responses/1.json
  def destroy
    @response.destroy
    respond_to do |format|
      format.html { redirect_to responses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_response
      @response = Response.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def response_params
      params.require(:response).permit(:event_id, :atending, :arivle_time, :deparcher_time, :user_id)
    end
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/responses/_form.html.erb
<%= form_for(@response) do |f| %>
  <% if @response.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@response.errors.count, "error") %> prohibited this response from being saved:</h2>

      <ul>
      <% @response.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :atending %><br>
    <%= f.check_box :atending %>
  </div>
  <div class="field">
    <%= f.label :arivle_time %><br>
    <%= f.datetime_select :arivle_time %>
  </div>
  <div class="field">
    <%= f.label :deparcher_time %><br>
    <%= f.datetime_select :deparcher_time %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/responses/edit.html.erb
<h1>Editing response</h1>

<%= render 'form' %>

<%= link_to 'Show', @response %> |
<%= link_to 'Back', responses_path %>

app/views/responses/index.html.erb
<h1>Listing responses</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Atending</th>
      <th>Arivle time</th>
      <th>Deparcher time</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @responses.each do |response| %>
      <tr>
        <td><%= response.atending %></td>
        <td><%= response.arivle_time %></td>
        <td><%= response.deparcher_time %></td>
        <td><%= response.user_id %></td>
        <td><%= link_to 'Show', response %></td>
        <td><%= link_to 'Edit', edit_response_path(response) %></td>
        <td><%= link_to 'Destroy', response, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Response', new_response_path %>

app/views/responses/new.html.erb
<h1>New response</h1>

<%= render 'form' %>

<%= link_to 'Back', responses_path %>

app/views/responses/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>event:</strong>
  <%= @response.event.name %>
</p>
<p>
  <strong>host:</strong>
  <%= @response.event.host.name %>
</p>
<p>
  <% if @response.atending == true%>
    <strong>Im Atending!!</strong>

    <p>
      <strong>Arivle time:</strong>
      <%= @response.arivle_time.strftime("%B %d, %Y at %I:%M%P") %>
    </p>
    <p>
      <strong>Deparcher time:</strong>
      <%= @response.deparcher_time.strftime("%B %d, %Y at %I:%M%P") %>
    </p>

  <% elsif @response.atending == false %>
    <strong>Im not atending :(</strong>
  <% else %>
    <strong>are you going to atend?</strong>
    <%= render 'form' %>
  <% end %>

</p>



<p>
  <strong>User:</strong>
  <%= @response.user_id %>
</p>

<%= link_to 'Edit', edit_response_path(@response) %> |
<%= link_to 'Back', responses_path %>